name: Deploy Sphinx documentation to Pages

on:
  push:
  pull_request:
    branches: [master] # branch to trigger deployment

jobs:
  doxygen:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
    - name: Get latest code
      run: |
        rm -rf qelectrotech-source-mirror
        # test only, remove when merging
        git clone --recursive https://github.com/Int-Circuit/qelectrotech-source-mirror.git
        cd qelectrotech-source-mirror
        git fetch
        git switch ci/cd
        cd ..

        # git clone --recursive https://github.com/qelectrotech/qelectrotech-source-mirror.git
    - uses: mattnotmitt/doxygen-action@v1.9.5
      with:
        working-directory: 'qelectrotech-source-mirror/'
        doxyfile-path: 'Doxyfile'
        enable-latex: true
    - uses: actions/upload-artifact@v4
      with:
       name: XML_Doxyfile 
       path: qelectrotech-source-mirror/doc/xml/
  pages:
    needs: [doxygen]
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v4
      with:
        name: XML_Doxyfile
        path: xml
    - name: Display structure of downloaded files
      run: ls -R xml
    - name: spell
      uses: codespell-project/actions-codespell@v2
      with:
        path: source
        exclude_file: ${{ github.workspace }}/source/conf.py
        skip:  .svg, .po, .sh, .py 
      continue-on-error: true
    - name: deployment
      uses: sphinx-notes/pages@v3
      with:
        documentation_path: ./source
        requirements_path: requirements.txt
        cache: true