name: Deploy Sphinx documentation to Pages

on:
  push:
  pull_request:
  # branch to trigger deployment
    branches: [master,
    #TESTING, REMOVE BEFORE MERGE            
              MR-next ] 

jobs:
  pages:
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - name: spell
      uses: codespell-project/actions-codespell@v2
      with:
        path: source
        exclude_file: ${{ github.workspace }}/source/conf.py
        skip:  .svg, .po, .sh, .py 
      continue-on-error: true
    - name: deployment
      uses: sphinx-notes/pages@v3
      with:
        documentation_path: ./source
        requirements_path: requirements.txt
        cache: true