name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [master,MR-next ]
    #TESTING, REMOVE BEFORE MERGE                 
  pull_request:
  # branch to trigger deployment
    branches: [master, MR-next ]
    #TESTING, REMOVE BEFORE MERGE            
               

jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: spell
      uses: codespell-project/actions-codespell@v2
      with:
        path: source
        exclude_file: ${{ github.workspace }}/source/conf.py
        skip:  '*.svg,*.py'
      continue-on-error: true
    - name: deployment
      uses: sphinx-notes/pages@v3
      with:
        documentation_path: ./source
        requirements_path: requirements.txt
        cache: true